version: 2
jobs:
  build:
    docker:
      - image: docker:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: apk add make curl
      - run: mkdir -vp ~/.docker/cli-plugins/
      - run: curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
      - run: chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run: docker buildx create --name multiarch --driver docker-container --use
      - run: docker buildx inspect --bootstrap
      - run: docker buildx ls
      - run: |
          docker buildx build --push \
            --platform linux/arm64,linux/amd64 \
            --tag dakue/docker-glauth:latest .

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: common
